### PR TITLE
Add ability for bot to tweet out recent comments on bio/medrxiv preprints

### PR DESCRIPTION
**Pull request by vincerubinetti**
- refactor code, split into multiple files by domain
- integrate Disqus api to pull latest comments from bio/medrxiv
- add ability to load keys in `.env` for local testing
- various other changes and improvements

### CODE REVIEW

**Comment by vincerubinetti** [comment]
If you'd like to test this locally without tweeting, and you have node installed, you can run `yarn comment:test` or `yarn preprint:test`.

**Comment by cgreene** [comment]
My mind is somewhat fried. I am seeing how this is getting the comments but not the rules by which comments are tweeted. Does it tweet all comments since the last one? Something else?

**Comment by vincerubinetti** [comment]
@cgreene the logic is here: https://github.com/greenelab/preprint-bot/pull/2/files#diff-3306170db2279a32106a29c8a32bb6defcbcb505b19087b94f456902a835d5eeR38

It sorts by likes, then by date, and finds the first one that hasn't been tweeted already and also returns results in preprint similarity search.

**Comment by cgreene** [comment]
👀 thank you for pointing that out! What do you think about increasing the cadence for disqus to hourly while we work through the backlog? The most downloaded ones could still fire daily.

**Comment by vincerubinetti** [comment]
We could do that. There's not very many, and we may end up tweeting very old comments though. Also Disqus api returns paginated results with a max page size of 100. Probably don't want to go above that since we might get rate limited due to other queries I need to make.

Another note: Right now I'm identifying duplicates by the preprint title, even when we're posting about a comment. So, if there are multiple comments on a preprint, only one will ever be tweeted.

There are many things we could tweak. Maybe we can workshop it in our meeting tomorrow.

**Comment by vincerubinetti** [comment]
@cgreene Can I have your blessing on the tweet template, for now. I'm going to merge this soon and work on a separate PR for storing the previous tweets in a "database". For now I've "disabled" the comment github action (set it to only run on Jan 1st) so it wont run.

### Comment tweet

image

### Preprint tweet

image

**Comment by cgreene** [comment]
Woo! :shipit:

**Comment by cgreene** [comment]
Oh - wait - one sec - does that bioRxiv link in the comment go to this paper or is that something that just happened to be included in the comment itself?

If so, I think we should link to the bioRxiv paper from here, and then if we can add a trailing comment/reply in a thread use that reply to share the preprint similarity search.

**Comment by vincerubinetti** [comment]
In the first screenshot, that link happens to be in the comment. That may not be the actual link of the preprint, but a link to another biorxiv preprint. I took out the actual biorxiv link to make room for the comment and title.

I'd like to save the reply design for another PR as well since it will require a bit of a refactor.

**Comment by cgreene** [comment]
I agree with saving that for another PR. It is not necessary for a viable product. 😁

**Comment by michaelmhoffman** [comment]
This is awesome! I would humbly like to suggest that the comment template save as much space as possible for the text of the comment. Here is a draft that uses less space for other stuff leaving more for the comment.

- uses "X et al." as seems more coherent than an equivalent short snippet of title
- uses display name of commenter
- uses > to block quote
- just has link to bioRxiv article at the end rather than similarity search

---

💬 bioRxiv comment on Emmenegger et al by johnshop:

> Aplp1 and the Aplp1-Lag3 Complex facilitates transmission of pathologic α-synuclein
https://www.biorxiv.org/con...
Which one should we believe? Why the GFP antibody was used to stain YFP? Artifacts? 

https://www.biorxiv.org/content/10.1101/2021.04.25.441302v1

**Comment by vincerubinetti** [comment]
@michaelmhoffman Re your suggestions:

1. Using author is cleaner imo but there will seemingly be duplicates for authors who have written many popular papers. I'd lean away from this.
2. Imo the author of the comment isn't really important as we're trying to draw attention to the preprint and our preprint similarity search service, specifically.
3. This is a twitter bot and block quotes or any kind of markdown isn't supported on twitter. I had to settle for separating sections of the tweet by blank lines.
4. @cgreene suggested this and we'll probably do it in another PR. I think click-through rate of replies is pretty low, so if we put PSS in a reply tweet, almost no one will click on it. But it would make things cleaner looking and perhaps less selfishly focus the bot on our own product.


@cgreene what are your thoughts on these

**Pull request merged**
